from .FigurateNum import FigurateNum
from .plane_figurate_numbers.PlaneFigurateNum import PlaneFigurateNum
from .space_figurate_numbers.SpaceFigurateNum import SpaceFigurateNum
from .multidimensional_figurate_numbers.MultidimensionalFigurateNum import MultidimensionalFigurateNum
from .NumCollector import NumCollector
